project 'MuscleDiary.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MuscleDiary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MuscleDiary
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireNetworkActivityIndicator'
  pod 'AlamofireObjectMapper', '~> 5.2.1'
  pod 'SnapKit'
  pod 'Kingfisher', '~> 5.0'
  # pod 'SwiftyJSON'
  # pod 'RealmSwift'
  
  # Drawer View Controller
  # pod 'KWDrawerController', '~> 4.2'
  # Star Rating Library
  # pod 'Cosmos', '~> 21.0'
  # pod 'TinyConstraints'
  # ImagePickerWith Crop
  # pod 'ALCameraViewController'
  # pod 'Mantis', '~> 1.0.0'
  
  pod 'Firebase/Analytics'
  # pod 'Fabric', '~> 1.10.2'
  # pod 'Crashlytics', '~> 3.14.0'
  pod 'Firebase/Crashlytics'
  # pod 'FirebaseStorage'

end
